version: '2.1'
services:

  scheduler:
    image: axiom/docker-luigi
    container_name: scheduler
    command: luigid
    ports:
      - "8082:8082"

  controller:
    image: tac-example
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}:/data
    environment:
      - DATA_DIR
    depends_on:
      - scheduler
